[application]


[web.app]
base_path = "bible-memory"

# HTML title tag content
title = "bible-memory"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
